package usecases

import (
	"bytes"
	"fmt"
)

// PrometheusMetrics - exports a prometheus compatible string
func PrometheusMetrics() string {
	metrics := Metrics() // Get the raw metrics
	var buffer bytes.Buffer

	buffer.WriteString("# HELP systeminfo_memory_bytes How much memory.\n")
	buffer.WriteString("# TYPE systeminfo_memory_bytes gauge\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_memory_bytes %v\n", metrics.Memory.Total))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_memory_available_bytes How much memory available.\n")
	buffer.WriteString("# TYPE systeminfo_memory_available_bytes gauge\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_memory_available_bytes %v\n", metrics.Memory.Available))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_memory_used_bytes How much memory available.\n")
	buffer.WriteString("# TYPE systeminfo_memory_used_bytes gauge\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_memory_used_bytes %v\n", metrics.Memory.Used))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_memory_used_percentage How much memory used as percentage.\n")
	buffer.WriteString("# TYPE systeminfo_memory_used_percentage gauge\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_memory_used_percentage %v\n", metrics.Memory.UsedPercent))
	buffer.WriteString("\n")
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_host_uptime How long been on\n")
	buffer.WriteString("# TYPE systeminfo_host_uptime counter\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_host_uptime %v\n", metrics.Host.Uptime))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_host_procs How Many Processes\n")
	buffer.WriteString("# TYPE systeminfo_host_procs guage\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_procs %v\n", metrics.Host.Procs))
	buffer.WriteString("\n")
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_load_1 Load Last Minute\n")
	buffer.WriteString("# TYPE systeminfo_load_1 guage\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_load_1 %v\n", metrics.Load.Load1))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_load_5 Load Last 5 Minute\n")
	buffer.WriteString("# TYPE systeminfo_load_5 guage\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_load_5 %v\n", metrics.Load.Load5))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_load_15 Load Last 15 Minute\n")
	buffer.WriteString("# TYPE systeminfo_load_15 guage\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_load_15 %v\n", metrics.Load.Load15))
	buffer.WriteString("\n")
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_cpu_cores Number or Cores\n")
	buffer.WriteString("# TYPE systeminfo_cpu_cores counter\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_cpu_cores %v\n", metrics.CPU.CPUCount))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_cpu_load load\n")
	buffer.WriteString("# TYPE systeminfo_cpu_load guage\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_cpu_load %v\n", metrics.CPU.CPULoad))
	buffer.WriteString("\n")
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_network_bytes_sent Network bytes sent\n")
	buffer.WriteString("# TYPE systeminfo_network_bytes_sent counter\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_network_bytes_sent %v\n", metrics.Network[0].BytesSent))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_network_bytes_received Network bytes received\n")
	buffer.WriteString("# TYPE systeminfo_network_bytes_received counter\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_network_bytes_received %v\n", metrics.Network[0].BytesRecv))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_network_packets_sent Network packets sent\n")
	buffer.WriteString("# TYPE systeminfo_network_packets_sent counter\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_network_packets_sent %v\n", metrics.Network[0].PacketsSent))
	buffer.WriteString("\n")
	buffer.WriteString("# HELP systeminfo_network_packets_received Network packets received\n")
	buffer.WriteString("# TYPE systeminfo_network_packets_received counter\n")
	buffer.WriteString(fmt.Sprintf("systeminfo_network_packets_received %v\n", metrics.Network[0].PacketsRecv))
	buffer.WriteString("\n")

	return buffer.String()
}
